### ISSUE TITLE
The Printing Commands like 8ball and f with a reason can often bring up the help menu when used >help

### ISSUE THREAD

**Issue by Krypton279** [hackarmour/discord-assistant-js#5]
>f @assistant
>8ball @Assistant

these commands often bring up weird outputs where it gives help screen and also the reason for saying f aswell or even after answering 8ball questions

**Comment by itsmebirdie** [comment]
This issue is related to [discord-assistant-py](https://github.com/hackarmour/discord-assistant-py) and not [discord-assistant-js](https://github.com/hackarmour/discord-assistant-js).
If you wouldn't mind to move the issue to the concurrent version of Discord Assistant related to this issue at [discord-assistant-py](https://github.com/hackarmour/discord-assistant-py/issues).
